site_name: {{cookiecutter.project_name}}
nav:
  - Home: index.md
  - API: API.md
theme: 
  name: material
  palette:
  # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - swagger-ui-tag
  - mkdocstrings:
      default_handler: python

