site_name: Mkdocs_cookiecutter
nav:
  - Home: index.md
  - Hooks: hooks.md
  - CookieCutter: cookiecutter.md
theme: 
  name: material
  logo: favicon.png
  favicon: favicon.png
  
  
  palette:
  - media: "(prefers-color-scheme)"
    primary: deep orange
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    primary: deep orange
    scheme: default
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: deep orange
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to system preference


plugins:
- search
- mkdocstrings:
    default_handler: python
- table-reader